<?php

namespace app\api\controller;

use app\common\controller\Commonattestation;
use app\common\controller\Commonuser;
use think\Controller;
use think\Db;
/**
 * Created by PhpStorm.
 * User:lang
 * time:2024年11月07月 16:31:43
 * ps:账户操作方法
 */
class Account extends Gathercontroller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:POST, GET, PUT, DELETE, OPTIONS');
        header('Access-Control-Allow-Credentials: true');
        header('Access-Control-Allow-Headers:*');
        header('Access-Control-Expose-Headers: *');
    }
    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年11月07月 16:39:10
     * ps:获取账户信息
     * url:{{URL}}/index.php/api/account/getaccount
     */
    public function getaccount(){
        $type = input('param.type');
        $typeId = input('param.typeId');
        if(!$type || !$typeId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        $account = Db::name('account')->where('type','=',$type)->where('type_id','=',$typeId)->find();
        $data = array();
        $data['rechargeMoney'] = $account['rechargeMoney'];
        $data['withdrawalMoney'] = $account['withdrawalMoney'];
        $data['frozenMoney'] = $account['frozenMoney'];
        $data['balance'] = $account['balance'];
        $data['template'] = $account['template'];
        $data['contract'] = $account['contract'];
        $data['usecontract'] = $account['usecontract'];
        $data['usetemplate'] = $account['usetemplate'];
        ajaxReturn(['code'=>200,'msg'=>'获取成功','data'=>$data]);
    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年11月07月 17:13:17
     * ps:提现
     * url:{{URL}}/index.php/api/account/withdrawal
     */
    public function withdrawal(){

    }
}