<?php

namespace app\api\controller;

use app\common\controller\Commonattestation;
use app\common\controller\Commoncontract;
use app\common\controller\Commonenter;
use app\common\controller\Commoninfo;
use app\common\controller\Commonuser;
use think\Controller;
use think\Db;

class Contract extends Gathercontroller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:POST, GET, PUT, DELETE, OPTIONS');
        header('Access-Control-Allow-Credentials: true');
        header('Access-Control-Allow-Headers:*');
        header('Access-Control-Expose-Headers: *');

    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年9月19月 17:33:32
     * ps:合同列表（我收到、我发起、抄送我）
     * url:{{URL}}/index.php/api/contract/contractlist
     */
   public function contractlist(){
       $type = input('param.type');
       $typeId = input('param.typeId');
       $listtype = input('param.listtype');//1:我收到；2：我发起；3：抄送我
       $search = input('search');
       $state = input('state');
       $page = input('page');
       $limit = input('limit');
       $taskId = input('param.taskId');//任务id
       if(!$limit){
           $limit = 10;
       }
       if(!$type){
           ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
       }
       if(!$typeId){
           ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
       }
       if(!$listtype){
           ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
       }

       if($listtype == 1){
           $whereor = '';
           if($search){
               $whereor = " `contract`.`contractName` LIKE '%$search%'
                           OR `contract`.`involvedName` LIKE '%$search%'";
           }
           $stwhere = array();
           if($state){

               $stwhere['contract.state'] = $state;
               if($state == 50){
                   $stwhere = array();
               }
           }else{
               if($state == 0){
                   $stwhere['contract.state'] = 0;
               }
           }

           //我收到
           $contract = Db::name('contract_signing as s')
               ->join('contract','contract.id=s.contract_id')
               ->where($whereor)
               ->where('s.type','=',$type)
               ->where('s.type_id','=',$typeId)
               ->where('contract.initiate_id','<>',$typeId)
               ->where($stwhere)
               ->order('contract.id desc')
               ->page($page,$limit)
               ->select();
           $count = Db::name('contract_signing as s')
               ->join('contract','contract.id=s.contract_id')
               ->where('s.type','=',$type)
               ->where('s.type_id','=',$typeId)
               ->where($stwhere)
               ->where('contract.initiate_id','<>',$typeId)
               ->order('contract.id desc')
               ->count();
       }else if($listtype == 2){
           $stwhere = array();
           if($state){
               $stwhere['state'] = $state;
               if($state == 50){
                   $stwhere = array();
               }
           }else{
               if($state == 0){
                   $stwhere['state'] = 0;
               }
           }
           $whereor = '';
           if($search){
               $whereor = "`contractName` LIKE '%$search%'
               OR `involvedName` LIKE '%$search%'";
           }
           $where = array();
           if($taskId){
               $where['task_id'] = $taskId;
           }
           //我发起的
           $contract = Db::name('contract')
               ->where($whereor)
               ->where($where)
               ->where('initiateType','=',$type)
               ->where('initiate_id','=',$typeId)
               ->where($stwhere)
               ->order('id desc')
               ->page($page,$limit)
               ->field('id as contract_id,initiateType,initiate_id,contractNo,contractName,state,createtime')
               ->select();

           $count = Db::name('contract')
               ->where($whereor)
               ->where('initiateType','=',$type)
               ->where('initiate_id','=',$typeId)
               ->where($stwhere)
               ->order('id desc')
               ->count();
           //用户合同列表，查询是否有示例合同
           $example = Db::name('contract')
               ->where($whereor)
               ->where($where)
               ->where($stwhere)
               ->where('example','=',1)
               ->field('id as contract_id,initiateType,initiate_id,contractNo,contractName,state,createtime')
               ->find();
               if($example){
                   $count +=1;
               }


       }else if($listtype == 3){
           //抄送我的
           $whereor = '';
           if($search){
               $whereor = " `contract`.`contractName` LIKE '%$search%'
                           OR `contract`.`involvedName` LIKE '%$search%'";
           }
           $stwhere = array();
           if($state){
               $stwhere['contract.state'] = $state;
               if($state == 50){
                   $stwhere = array();
               }
           }else{
               if($state == 0){
                   $stwhere['contract.state'] = 0;
               }
           }
           $contract = Db::name('contract_macf as m')
               ->join('contract','contract.id=m.contract_id')
               ->where($whereor)
               ->where('m.type','=',$type)
               ->where('m.type_id','=',$typeId)
               ->where($stwhere)
               ->order('contract.id desc')
               ->page($page,$limit)
               ->select();
           $count = Db::name('contract_macf as m')
               ->join('contract','contract.id=m.contract_id')
               ->where($whereor)
               ->where('m.type','=',$type)
               ->where('m.type_id','=',$typeId)
               ->where($stwhere)
               ->count();
       }else if($listtype == 4){
           //待我操作
           $whereor = '';
           if($search){
               $whereor = "`contract`.`contractName` LIKE '%$search%'";
           }
           $contract = Db::name('contract_signing as s')
               ->join('contract','contract.id=s.contract_id')
               ->where($whereor)
               ->where('s.type','=',$type)
               ->where('s.type_id','=',$typeId)
               ->where('s.state','=',0)
               ->whereNotIn('contract.state', [3, 10, 7])
               ->order('contract.id desc')
               ->page($page,$limit)
               ->select();
           $count = Db::name('contract_signing as s')
               ->join('contract','contract.id=s.contract_id')
               ->where('s.type','=',$type)
               ->where('s.type_id','=',$typeId)
               ->where('s.state','=',0)
               ->whereNotIn('contract.state', [3, 10, 7])
               ->order('contract.id desc')
               ->count();
       }else if($listtype == 5){
           //待他人操作
           $whereor = '';
           if($search){
               $whereor = "`contract`.`contractName` LIKE '%$search%'";
           }
           $contract = Db::name('contract as c')
               ->join('contract_signing','c.id=contract_signing.contract_id')
               ->where($whereor)
               ->where('c.initiateType','=',$type)
               ->where('c.initiate_id','=',$typeId)
               ->where('contract_signing.type','<>',$type,'contract_signing.type_id','<>',$typeId)
               ->where('contract_signing.state','=',0)
               ->whereNotIn('c.state', [3, 10, 7])
               ->order('c.id desc')
               ->page($page,$limit)
               ->select();
           $count = Db::name('contract as c')
               ->join('contract_signing','c.id=contract_signing.contract_id')
               ->where($whereor)
               ->where('c.initiateType','=',$type)
               ->where('c.initiate_id','=',$typeId)
               ->where('contract_signing.type','<>',$type,'contract_signing.type_id','<>',$typeId)
               ->where('contract_signing.state','=',0)
               ->whereNotIn('c.state', [3, 10, 7])
               ->count();
       }else if($listtype == 6){
           //已完成
           $whereor = '';
           if($search){
               $whereor = "`contract`.`contractName` LIKE '%$search%'";
           }

           $contract = Db::name('contract_signing as s')
               ->join('contract','contract.id=s.contract_id')
               ->where($whereor)
               ->where('s.type','=',$type)
               ->where('s.type_id','=',$typeId)
               ->where('contract.state','=',2)
               ->order('contract.id desc')
               ->page($page,$limit)
               ->select();
           $count = Db::name('contract_signing as s')
               ->join('contract','contract.id=s.contract_id')
               ->where('s.type','=',$type)
               ->where('s.type_id','=',$typeId)
               ->where('contract.state','=',2)
               ->order('contract.id desc')
               ->count();
       }
       $data = array();
       $common = new \app\common\controller\Common();
       foreach($contract as $k=>$v){
           $data[$k]['contractId'] = $v['contract_id'];
           $data[$k]['contractNo'] = $v['contractNo'];

           $data[$k]['contractName'] = $v['contractName'];
           $data[$k]['initiateType'] = $v['initiateType'];
           $data[$k]['initiate_id'] = $v['initiate_id'];
           if($v['initiateType'] == 'custom'){
               $data[$k]['initiateName'] = $common->getcustom($v['initiate_id'],'name')['name'];
           }else{
               $data[$k]['initiateName'] = $common->getenter($v['initiate_id'],'name')['name'];
           }
           $data[$k]['state'] = $v['state'];
           if($v['state'] == 0){
               $data[$k]['stateName'] = '待签约';
           }else if($v['state'] == 1){
               $data[$k]['stateName'] = '签约中';
           }else if($v['state'] == 2){
               $data[$k]['stateName'] = '已签约';
           }else if($v['state'] == 3){
               $data[$k]['stateName'] = '已过期';
           }else if($v['state'] == 4){
               $data[$k]['stateName'] = '已拒签';
           }else if($v['state'] == 5){
               $data[$k]['stateName'] = '未发起';
           }else if($v['state'] == 6){
               $data[$k]['stateName'] = '已作废';
           }else if($v['state'] == 7){
               $data[$k]['stateName'] = '已撤销';
           }else if($v['state'] == 10){
               $data[$k]['stateName'] = '待发起';
           }
           $data[$k]['signing'] = array();
           $signing = Db::name('contract_signing')->where('contract_id','=',$v['contract_id'])->order('id desc')->select();
           foreach($signing as $kk=>$vv){


               $data[$k]['signing'][$kk]['type'] = $vv['type'];
               $data[$k]['signing'][$kk]['typeId'] = $vv['type_id'];
               if($vv['type'] == 'custom'){
                   $data[$k]['signing'][$kk]['typeName'] = $common->getcustom($vv['type_id'],'name')['name'];
               }else{
                   $data[$k]['signing'][$kk]['typeName'] = $common->getenter($vv['type_id'],'name')['name'];
               }
               $data[$k]['signing'][$kk]['state'] = $vv['state'];
               if($vv['state'] == 0){
                   $data[$k]['signing'][$kk]['stateName'] = '未签署';
               }else if($vv['state'] == 1){
                   $data[$k]['signing'][$kk]['stateName'] = '已签署';
               }else if($vv['state'] == 2){
                   $data[$k]['signing'][$kk]['stateName'] = '拒绝签署';
               }
           }
           $data[$k]['createtime'] = date('Y-m-d H:i:s',$v['createtime']);

       }
       $sumpage = 0;
       $sumpage  = ceil($count/$limit);
       if($listtype == 2){
           if($example) {
               //dump($example);exit;
               //判断是否最后一页才展示示例合同
               if($page == $sumpage){
                   $numk = count($data);
                   $data[$numk]['contractId'] = $example['contract_id'];
                   $data[$numk]['contractNo'] = $example['contractNo'];

                   $data[$numk]['contractName'] = $example['contractName'];
                   $data[$numk]['initiateType'] = $example['initiateType'];
                   $data[$numk]['initiate_id'] = $example['initiate_id'];
                   if($example['initiateType'] == 'custom'){
                       $data[$numk]['initiateName'] = $common->getcustom($example['initiate_id'],'name')['name'];
                   }else{
                       $data[$numk]['initiateName'] = $common->getenter($example['initiate_id'],'name')['name'];
                   }
                   $data[$numk]['state'] = $example['state'];
                   if($example['state'] == 0){
                       $data[$numk]['stateName'] = '待签约';
                   }else if($example['state'] == 1){
                       $data[$numk]['stateName'] = '签约中';
                   }else if($example['state'] == 2){
                       $data[$numk]['stateName'] = '已签约';
                   }else if($example['state'] == 3){
                       $data[$numk]['stateName'] = '已过期';
                   }else if($example['state'] == 4){
                       $data[$numk]['stateName'] = '已拒签';
                   }else if($example['state'] == 5){
                       $data[$numk]['stateName'] = '未发起';
                   }else if($example['state'] == 6){
                       $data[$numk]['stateName'] = '已作废';
                   }else if($example['state'] == 7){
                       $data[$numk]['stateName'] = '已撤销';
                   }else if($example['state'] == 10){
                       $data[$numk]['stateName'] = '待发起';
                   }
                   $data[$numk]['signing'] = array();
                   $signing = Db::name('contract_signing')->where('contract_id','=',$example['contract_id'])->order('id desc')->select();
                   foreach($signing as $kk=>$vv){


                       $data[$numk]['signing'][$kk]['type'] = $vv['type'];
                       $data[$numk]['signing'][$kk]['typeId'] = $vv['type_id'];
                       if($vv['type'] == 'custom'){
                           $data[$numk]['signing'][$kk]['typeName'] = $common->getcustom($vv['type_id'],'name')['name'];
                       }else{
                           $data[$numk]['signing'][$kk]['typeName'] = $common->getenter($vv['type_id'],'name')['name'];
                       }
                       $data[$numk]['signing'][$kk]['state'] = $vv['state'];
                       if($vv['state'] == 0){
                           $data[$numk]['signing'][$kk]['stateName'] = '未签署';
                       }else if($vv['state'] == 1){
                           $data[$numk]['signing'][$kk]['stateName'] = '已签署';
                       }else if($vv['state'] == 2){
                           $data[$numk]['signing'][$kk]['stateName'] = '拒绝签署';
                       }
                   }
                   $data[$numk]['createtime'] = date('Y-m-d H:i:s',$example['createtime']);
               }
           }
       }
       ajaxReturn(['code'=>200,'msg'=>'获取成功','data'=>$data,'page'=>$page,'limit'=>$limit,'sum_page'=>$sumpage]);

   }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年9月20月 10:55:31
     * ps:合同各类型总数
     * url:{{URL}}/index.php/api/contract/getcontractcount
     */
   public function getcontractcount(){
       $type = input('param.type');
       $typeId = input('param.typeId');

       if(!$type){
           ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
       }
       if(!$typeId){
           ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
       }

           $receive = Db::name('contract_signing as s')
               ->join('contract','contract.id=s.contract_id')
               ->where('s.type','=',$type)
               ->where('s.type_id','=',$typeId)
               ->where('contract.initiateType','<>',$type,'contract.initiate_id','<>',$typeId)
               ->count();
           $initiate = Db::name('contract')
               ->where('initiateType','=',$type)
               ->where('initiate_id','=',$typeId)
               ->count();
           $sendcopy = Db::name('contract_macf as m')
               ->join('contract','contract.id=m.contract_id')
               ->where('m.type','=',$type)
               ->where('m.type_id','=',$typeId)
               ->count();
           $ioperate = Db::name('contract_signing as s')
               ->join('contract','contract.id=s.contract_id')
               ->where('s.type','=',$type)
               ->where('s.type_id','=',$typeId)
               ->where('s.state','=',0)
               ->whereNotIn('contract.state', [3, 10, 7])

               ->count();
           $heoperate = Db::name('contract as c')
               ->join('contract_signing','c.id=contract_signing.contract_id')
               ->where('c.initiateType','=',$type)
               ->where('c.initiate_id','=',$typeId)
               ->where('contract_signing.type','<>',$type,'contract_signing.type_id','<>',$typeId)
               ->where('contract_signing.state','=',0)
               ->whereNotIn('c.state', [3, 10, 7])
               ->count();
       $finish = Db::name('contract_signing as s')
           ->join('contract','contract.id=s.contract_id')
           ->where('s.type','=',$type)
           ->where('s.type_id','=',$typeId)
           ->where('contract.state','=',2)
           ->count();
       $data['receive'] = $receive;
       $data['initiate'] = $initiate;
       $data['sendcopy'] = $sendcopy;
       $data['ioperate'] = $ioperate;
       $data['heoperate'] = $heoperate;
       $data['finish'] = $finish;
       ajaxReturn(['code'=>200,'msg'=>'获取成功','data'=>$data]);
   }


   public function test(){

       $data[0]['name'] = '法定代表人名称';
       $data[0]['type'] = 1;
       $data[0]['describe'] = '';
       $data[0]['content'] = '郎大大';
       $data[1]['name'] = '法人身份证号';
       $data[1]['type'] = 1;
       $data[1]['describe'] = '';
       $data[1]['content'] = '211282200001143815';
       $data[2]['name'] = '单位名称';
       $data[2]['type'] = 1;
       $data[2]['describe'] = '';
       $data[2]['content'] = '奥博森科技有限公司';
       $data[3]['name'] = '处室';
       $data[3]['type'] = 1;
       $data[3]['describe'] = '';
       $data[3]['content'] = '研发部';
       $data[4]['name'] = '负责人姓名';
       $data[4]['type'] = 1;
       $data[4]['describe'] = '';
       $data[4]['content'] = '郎骁';
       $data[5]['name'] = '负责人证件号';
       $data[5]['type'] = 1;
       $data[5]['describe'] = '';
       $data[5]['content'] = '211282200001143815';
       $rest = json_encode($data);
       print_r($rest);
   }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年9月20月 14:32:57
     * ps:通过模版生成合同
     * url:{{URL}}/index.php/api/contract/templatecontract
     */
    public function templatecontract(){
        $type = input('param.type');
        $typeId = input('param.typeId');
        $contractName = input('param.contractName');
        $expireTime = input('param.expireTime');//时间戳
        $signingTime = input('param.signingTime');//时间戳
        $templateId = input('param.templateId');
        $annex = input('param.annex');
        $content = input('param.content');//模板内容
        $signature = input('param.signature');//签署人信息
        $macf = input('param.macf');//抄送人信息

        $taskId = input('param.taskId');//批量签署任务id
        if(!$type){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        if(!$typeId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        if(!$contractName){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        if(!$templateId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        if(!$content){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        if(!$signature){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }

        //参与人名称记录
        $involvedName = '';
        $commoninfo = new Commoninfo();
        //发起人信息
        if($type == 'custom'){
            $name = $commoninfo->getcustom($typeId,'name')['name'];
        }else{
            $name = $commoninfo->getenter($typeId,'name')['name'];
        }
        //参与人名称记录
        $involvedName .= $name.';';

        //查询状态余额是否充足
//        $account = Db::name('account')->where('type','=',$type)->where('type_id','=',$typeId)->find();
//        if($account['contract'] < 1){
//            ajaxReturn(['code'=>330,'msg'=>'账户余额不足，无法生成合同']);
//        }
        $commoncontract = new Commoncontract();
        //添加合同信息
        $data['contractNo'] = $commoncontract->addcontractNo($this->platformId);
        $data['contractName'] = $contractName;
        $data['expireTime'] = $expireTime;
        $data['signingTime'] = $signingTime;
        $data['template_id'] = $templateId;
        $data['state'] = 10;//待发起合同状态

        $data['template'] = 1;
        if($taskId){
            //如果是从任务里来的则记录任务id
            $data['task_id'] = $taskId;
        }
        $contractId =$commoncontract->operatecontract($data,$type,$typeId);
        //添加合同模版内容
        $json_content = json_decode($content,true);
        foreach($json_content as $k=>$v){
            $condata['contract_id'] = $contractId;
            $condata['name'] = $v['name'];
            $condata['describe'] = $v['describe'];
            $condata['type'] = $v['type'];
            $condata['content'] = $v['content'];
            $condata['createtime'] = time();
            Db::name('contract_template_content')->insertGetId($condata);
            //验证必填项是否必填，不必填删除合同并且返回错误
            if($v['must'] == 1){
                if(!$v['content']){
                    //删除合同、合同内容
                    Db::name('contract')->where('id','=',$contractId)->delete();
                    Db::name('contract_template_content')->where('contract_id','=',$contractId)->delete();
                    ajaxReturn(['code'=>300,'msg'=>'请填写必填项']);
                }
            }
        }
        //添加合同签署方
        $commonuser= new Commonuser();
        $commonenter = new Commonenter();
        $json_signature = json_decode($signature,true);

        foreach($json_signature as $k=>$v){
            //判断是否填入签署人信息，如果有未填入的则提示错误并删除合同信息
            if(!$v['name']){
                //删除合同信息
                Db::name('contract')->where('id','=',$contractId)->delete();
                Db::name('contract_template_content')->where('contract_id','=',$contractId)->delete();
                Db::name('contract_signing')->where('contract_id','=',$contractId)->delete();

                ajaxReturn(['code'=>301,'msg'=>'请填写签署人']);
            }
            if($v['type'] == 'custom'){
                //个人用户
                $custom = Db::name('custom')->where('phone','=',$v['phone'])->find();
                if(!$custom){
                    $cudata['name'] = $v['name'];
                    $cudata['phone'] = $v['phone'];
                    $customId = $commonuser->operatecustom($cudata);
                }else{
                    $signdata['account'] = $custom['account'];
                    $customId = $custom['id'];
                }
                $signdata['type'] = $v['type'];
                $signdata['type_id'] = $customId;
                $signdata['custom_id'] = $customId;
                //参与人名称记录
                $involvedName .= $v['name'].';';
            }else{
                //参与人名称记录
                $involvedName .= $v['entername'].';';
                //企业用户
                $enter = Db::name('enterprise')->where('name','=',$v['entername'])->find();
                $custom = Db::name('custom')->where('phone','=',$v['phone'])->find();
                if(!$custom){
                    $cudata['name'] = $v['name'];
                    $cudata['phone'] = $v['phone'];
                    $customId = $commonuser->operatecustom($cudata);
                }else{
                    $customId = $custom['id'];
                }
                if(!$enter){
                    $endata['name'] = $v['entername'];
                    $enterId = $commonenter->operateenter($endata);
                }else{
                    $signdata['account'] = $enter['account'];

                    $enterId = $enter['id'];
                }
                $encu = Db::name('enterprise_custom')->where('enterprise_id','=',$enterId)->where('custom_id','=',$customId)->find();
                if(!$encu){
                    $encudata['enterprise_id'] = $enterId;
                    $encudata['custom_id'] = $customId;
                    $encudata['createtime'] = time();
                    $encuId = Db::name('enterprise_custom')->insertGetId($encudata);
                    $commonenter->addmember($encuId);
                }
                $signdata['type'] = $v['type'];
                $signdata['type_id'] = $enterId;
                $signdata['custom_id'] = $customId;
            }
            $signdata['TCN'] = $v['TCN'];
            $signdata['createtime'] = time();
            $signdata['contract_id'] = $contractId;
            if($signdata['type_id']){
                Db::name('contract_signing')->insertGetId($signdata);
            }

            //添加相对方
            if($typeId ==$signdata['type_id'] && $type ==$signdata['type']){

            }else{
                $counterpart = Db::name('counterpart')
                    ->where('ownerType','=',$type)
                    ->where('owner_id','=',$typeId)
                    ->where('type','=',$signdata['type'])
                    ->where('type_id','=',$signdata['type_id'])->find();
                //如果没有相对方就添加
                if(!$counterpart){
                    $cpartdata['ownerType'] = $type;
                    $cpartdata['owner_id'] = $typeId;
                    $cpartdata['type'] = $signdata['type'];
                    $cpartdata['type_id'] = $signdata['type_id'];
                    $cpartdata['createtime'] = time();
                    Db::name('counterpart')->insertGetId($cpartdata);
                }
            }

        }
        $json_annex = json_decode($annex,true);
        foreach($json_annex as $k=>$v){
            $annexdata['contract_id'] = $contractId;
            $annexdata['name'] = $v['name'];
            $annexdata['file'] = $v['file'];
            $annexdata['createtime'] = time();
            Db::name('contract_annex')->insertGetId($annexdata);
        }

        $json_macf = json_decode($macf,true);
        foreach($json_macf as $k=>$v){
            if($v['type'] == 'custom'){
                //个人用户
                $custom = Db::name('custom')->where('phone','=',$v['phone'])->find();
                if(!$custom){
                    $cudata['name'] = $v['name'];
                    $cudata['phone'] = $v['phone'];
                    $customId = $commonuser->operatecustom($cudata);
                }else{
//                    $macfdata['account'] = $custom['account'];

                    $customId = $custom['id'];
                }
                $macfdata['type'] = $v['type'];
                $macfdata['type_id'] = $customId;
                $macfdata['custom_id'] = $customId;
            }else{
                //企业用户
                $enter = Db::name('enterprise')->where('name','=',$v['entername'])->find();
                $custom = Db::name('custom')->where('phone','=',$v['phone'])->find();
                if(!$custom){
                    $cudata['name'] = $v['name'];
                    $cudata['phone'] = $v['phone'];
                    $customId = $commonuser->operatecustom($cudata);
                }else{
                    $customId = $custom['id'];
                }
                if(!$enter){
                    $endata['name'] = $v['entername'];
                    $enterId = $commonenter->operateenter($endata);
                }else{

                    $enterId = $enter['id'];
                }
                $encu = Db::name('enterprise_custom')->where('enterprise_id','=',$enterId)->where('custom_id','=',$customId)->find();
                if(!$encu){
                    $encudata['enterprise_id'] = $enterId;
                    $encudata['custom_id'] = $customId;
                    $encudata['createtime'] = time();
                    $ecId = Db::name('enterprise_custom')->insertGetId($encudata);
                    $commonenter->addmember($ecId);
                }
                $macfdata['type'] = $v['type'];
                $macfdata['type_id'] = $enterId;
                $macfdata['custom_id'] = $customId;
            }
            $macfdata['createtime'] = time();
            $macfdata['contract_id'] = $contractId;
            Db::name('contract_macf')->insertGetId($macfdata);

        }
        //填入参与人
        $editinvo['involvedName'] = $involvedName;
        $commoncontract->operatecontract($editinvo,$type,$typeId,$contractId);

        $res = $commoncontract->initiatecontract($contractId);

        if($res['code'] == 200){
            ajaxReturn(['code'=>200,'msg'=>'生成成功','contractId'=>$contractId,'url'=>$res['url']]);
        }else{
            $commoncontract->delcontract($contractId);
            ajaxReturn(['code'=>303,'msg'=>$res['msg']]);
        }
    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年9月20月 16:05:52
     * ps:获取合同地址(请求为签署方且未签署获取签署地址；其他为详情地址)
     * url:{{URL}}/index.php/api/contract/getcontracturl
     */
    public function getcontracturl(){
        $type = input('param.type');
        $typeId = input('param.typeId');
        $contractId = input('param.contractId');
        $redirectUrl = input('param.redirectUrl');
        $port = input('param.port');//0：公众号；1：小程序

        if(!$type){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        if(!$typeId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }

        $sign = Db::name('contract_signing')->where('type','=',$type)->where('type_id','=',$typeId)->where('contract_id','=',$contractId)->find();
        $contract = Db::name('contract')->where('id','=',$contractId)->find();
        //判断进入人是否是合同参与人
        //不是示例合同
        if($contract['example'] == 0){
            $signpeople = 1;//1代表是参与人
            $contractpeople = 1;
            $macfpeople = 1;
            if(!$sign){
                $signpeople = 0;
            }
            if($contract['initiateType'] != $type && $contract['initiate_id'] != $typeId){
                $contractpeople = 0;
            }
            $macf = Db::name('contract_macf')->where('type','=',$type)->where('type_id','=',$typeId)->find();
            if(!$macf){
                $macfpeople = 0;
            }
            if($signpeople == 0 && $contractpeople == 0 && $macfpeople == 0){
                ajaxReturn(['code'=>303,'msg'=>'无权限查看该合同']);
            }
        }

        $commoncontract = new Commoncontract();
        $url = '';
        if($contract['state'] == 10){
            //未发起状态合同
            $res = $commoncontract->getapicontracturl($contractId);
        }else if($contract['state'] == 6){
            //作废合同
            $res = $commoncontract->getapicontracturl($contractId);
        }else if($contract['state'] == 7){
            //撤销合同
            $res = $commoncontract->getapicontracturl($contractId);
        }else if($contract['state'] == 3){
            //过期合同
            $res = $commoncontract->getapicontracturl($contractId);
        } else{
            if($sign){
                if($sign['state'] == 0){
                    $res = $commoncontract->getsignerurl($sign['id'],$redirectUrl,$port);
                }else{
                    $res = $commoncontract->getapicontracturl($contractId);
                }
            }else{
                $res = $commoncontract->getapicontracturl($contractId);
            }
        }

        if($res['code'] == 200){
            ajaxReturn(['code'=>200,'msg'=>'获取成功','url'=>$res['url']]);

        }else{
            ajaxReturn(['code'=>303,'msg'=>$res['msg']]);
        }
    }


    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年9月23月 14:42:03
     * ps:发起合同（上传文件）
     * url:{{URL}}/index.php/api/contract/filecontract
     */
    public function filecontract(){
        $type = input('param.type');
        $typeId = input('param.typeId');
        $contractName = input('param.contractName');
        $expireTime = input('param.expireTime');//时间戳
        $file = input('param.file');//合同文件
        $filename = input('param.filename');//合同名称带后缀
        $signature = input('param.signature');//签署人信息
        $annex = input('param.annex');//合同附件（文件地址逗号隔开）
        $signingTime = input('param.signingTime');//时间戳
        $macf = input('param.macf');//抄送人信息


        if(!$type){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        if(!$typeId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        if(!$contractName){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        if(!$signature){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        if(!$filename){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        if(!$file){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }

        //参与人名称记录
        $involvedName = '';
        $commoninfo = new Commoninfo();
        //发起人信息
        if($type == 'custom'){
            $name = $commoninfo->getcustom($typeId,'name')['name'];
        }else{
            $name = $commoninfo->getenter($typeId,'name')['name'];
        }
        //参与人名称记录
        $involvedName .= $name.';';

        //查询状态余额是否充足
//        $account = Db::name('account')->where('type','=',$type)->where('type_id','=',$typeId)->find();
//        if($account['contract'] < 1){
//            ajaxReturn(['code'=>330,'msg'=>'账户余额不足，无法生成合同']);
//        }

        //添加合同信息
        $commoncontract = new Commoncontract();
        $data['contractNo'] = $commoncontract->addcontractNo($this->platformId);
        $data['contractName'] = $contractName;
        $data['expireTime'] = $expireTime;
        $data['fileName'] = $filename;
        $data['contractFile'] = $file;
        $data['signingTime'] = $signingTime;
        $data['state'] = 10;

        $contractId =$commoncontract->operatecontract($data,$type,$typeId);
        //添加合同签署方
        $commonuser= new Commonuser();
        $commonenter = new Commonenter();
        $json_signature = json_decode($signature,true);
        foreach($json_signature as $k=>$v){
            //判断是否填入签署人信息，如果有未填入的则提示错误并删除合同信息
            if(!$v['name']){
                //删除合同信息
                Db::name('contract')->where('id','=',$contractId)->delete();
                ajaxReturn(['code'=>301,'msg'=>'请填写签署人']);
            }
            if($v['type'] == 'custom'){
                //个人用户
                $custom = Db::name('custom')->where('phone','=',$v['phone'])->find();
                if(!$custom){
                    $cudata['name'] = $v['name'];
                    $cudata['phone'] = $v['phone'];
                    $customId = $commonuser->operatecustom($cudata);
                }else{
                    $signdata['account'] = $custom['account'];

                    $customId = $custom['id'];
                }
                $signdata['type'] = $v['type'];
                $signdata['type_id'] = $customId;
                $signdata['custom_id'] = $customId;

                //参与人名称记录
                $involvedName .= $v['name'].';';
            }else{

                //参与人名称记录
                $involvedName .= $v['entername'].';';
                //企业用户
                $enter = Db::name('enterprise')->where('name','=',$v['entername'])->find();
                $custom = Db::name('custom')->where('phone','=',$v['phone'])->find();
                if(!$custom){
                    $cudata['name'] = $v['name'];
                    $cudata['phone'] = $v['phone'];
                    $customId = $commonuser->operatecustom($cudata);
                }else{
                    $customId = $custom['id'];
                }
                if(!$enter){
                    $endata['name'] = $v['entername'];
                    $enterId = $commonenter->operateenter($endata);
                }else{
                    $signdata['account'] = $enter['account'];

                    $enterId = $enter['id'];
                }
                $encu = Db::name('enterprise_custom')->where('enterprise_id','=',$enterId)->where('custom_id','=',$customId)->find();
                if(!$encu){
                    $encudata['enterprise_id'] = $enterId;
                    $encudata['custom_id'] = $customId;
                    $encudata['createtime'] = time();
                    Db::name('enterprise_custom')->insertGetId($encudata);
                }
                $signdata['type'] = $v['type'];
                $signdata['type_id'] = $enterId;
                $signdata['custom_id'] = $customId;
            }
            $signdata['TCN'] = '签署方'.$k;//$v['TCN'];
            $signdata['createtime'] = time();
            $signdata['contract_id'] = $contractId;
            Db::name('contract_signing')->insertGetId($signdata);
            //添加相对方
            if($typeId ==$signdata['type_id'] && $type ==$signdata['type']){

            }else{
                $counterpart = Db::name('counterpart')
                    ->where('ownerType','=',$type)
                    ->where('owner_id','=',$typeId)
                    ->where('type','=',$signdata['type'])
                    ->where('type_id','=',$signdata['type_id'])->find();
                //如果没有相对方就添加
                if(!$counterpart){
                    $cpartdata['ownerType'] = $type;
                    $cpartdata['owner_id'] = $typeId;
                    $cpartdata['type'] = $signdata['type'];
                    $cpartdata['type_id'] = $signdata['type_id'];
                    $cpartdata['createtime'] = time();
                    Db::name('counterpart')->insertGetId($cpartdata);
                }
            }
        }

        $json_annex = json_decode($annex,true);

        foreach($json_annex as $k=>$v){
            $annexdata['contract_id'] = $contractId;
            $annexdata['name'] = $v['name'];
            $annexdata['file'] = $v['file'];
            $annexdata['createtime'] = time();
            Db::name('contract_annex')->insertGetId($annexdata);
        }

        $json_macf = json_decode($macf,true);
        foreach($json_macf as $k=>$v){
            if($v['type'] == 'custom'){
                //个人用户
                $custom = Db::name('custom')->where('phone','=',$v['phone'])->find();
                if(!$custom){
                    $cudata['name'] = $v['name'];
                    $cudata['phone'] = $v['phone'];
                    $customId = $commonuser->operatecustom($cudata);
                }else{
//                    $macfdata['account'] = $custom['account'];

                    $customId = $custom['id'];
                }
                $macfdata['type'] = $v['type'];
                $macfdata['type_id'] = $customId;
                $macfdata['custom_id'] = $customId;
            }else{
                //企业用户
                $enter = Db::name('enterprise')->where('name','=',$v['entername'])->find();
                $custom = Db::name('custom')->where('phone','=',$v['phone'])->find();
                if(!$custom){
                    $cudata['name'] = $v['name'];
                    $cudata['phone'] = $v['phone'];
                    $customId = $commonuser->operatecustom($cudata);
                }else{
                    $customId = $custom['id'];
                }
                if(!$enter){
                    $endata['name'] = $v['entername'];
                    $enterId = $commonenter->operateenter($endata);
                }else{

                    $enterId = $enter['id'];
                }
                $encu = Db::name('enterprise_custom')->where('enterprise_id','=',$enterId)->where('custom_id','=',$customId)->find();
                if(!$encu){
                    $encudata['enterprise_id'] = $enterId;
                    $encudata['custom_id'] = $customId;
                    $encudata['createtime'] = time();
                    Db::name('enterprise_custom')->insertGetId($encudata);
                }
                $macfdata['type'] = $v['type'];
                $macfdata['type_id'] = $enterId;
                $macfdata['custom_id'] = $customId;
            }
            $macfdata['createtime'] = time();
            $macfdata['contract_id'] = $contractId;
            Db::name('contract_macf')->insertGetId($macfdata);

        }
        //填入参与人
        $editinvo['involvedName'] = $involvedName;
        $commoncontract->operatecontract($editinvo,$type,$typeId,$contractId);


        $res = $commoncontract->initiatecontractfile($contractId);
        if($res['code'] == 200){
            //扣除账户合同份数
//            $acedit['contract'] = $account['contract'] -1;
//            $acedit['usecontract'] = $account['usecontract'] +1;
//            $acedit['updatetime'] = time();
//            Db::name('account')->where('type','=',$type)->where('type_id','=',$typeId)->update($acedit);
            ajaxReturn(['code'=>200,'msg'=>'生成成功','contractId'=>$contractId,'url'=>$res['url']]);
        }else{
            ajaxReturn(['code'=>303,'msg'=>$res['msg']]);
        }
    }

    public function test3(){
        $data[0]['name'] = '附件1.png';
        $data[0]['file'] = 'https://sign.obsend.com/upload/image/20240923/4183e1bfde27bda0468bca3ae4da5744.png';
        $data[1]['name'] = '附件2.png';
        $data[1]['file'] = 'https://sign.obsend.com/upload/image/20240923/4183e1bfde27bda0468bca3ae4da5744.png';
        $rest = json_encode($data);
        print_r($rest);
    }
    public function test2(){
        $data[0]['name'] = '郎骁';
        $data[0]['type'] = 'enterprise';
        $data[0]['phone'] = '13841046298';
        $data[0]['entername'] = '辽宁鑫通网络货运有限公司';
        $data[0]['TCN'] = '甲方';
        $data[1]['name'] = '房璐伟';
        $data[1]['type'] = 'custom';
        $data[1]['phone'] = '17647696691';
        $data[1]['entername'] = '';
        $data[1]['TCN'] = '乙方';
        $rest = json_encode($data);
        print_r($rest);
    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月22月 10:23:14
     * ps:撤销合同
     * url:{{URL}}/index.php/api/contract/revoke
     */
    public function revoke(){
        $contractId = input('param.contractId');
        $type = input('param.type');
        $typeId = input('param.typeId');
        $reason = input('param.reason');
        if(!$contractId && $type && $typeId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        $contract = Db::name('contract')->where('id','=',$contractId)->find();
        if(!$contract){
            ajaxReturn(['code'=>301,'msg'=>'合同不存在']);
        }
        if($contract['state'] == 2){
            ajaxReturn(['code'=>301,'msg'=>'已签署合同无法撤销']);
        }
        if($contract['initiateType'] !=$type && $contract['initiate_id'] != $typeId){
            ajaxReturn(['code'=>301,'msg'=>'操作人不是合同发起人，撤销失败']);
        }
        $commoncontract = new Commoncontract();
        $res = $commoncontract->revokecontract($contractId,$reason);
        if($res['code'] == 200){
            ajaxReturn(['code'=>200,'msg'=>'操作成功']);
        }else{
            ajaxReturn(['code'=>303,'msg'=>'操作失败']);
        }

    }
    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月22月 10:28:58
     * ps:作废合同
     * url:{{URL}}/index.php/api/contract/cancel
     */
    public function cancel(){
        $contractId = input('param.contractId');
        $type = input('param.type');
        $typeId = input('param.typeId');
        $reason = input('param.reason');
        if(!$contractId && $type && $typeId && $reason){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }

        $contract = Db::name('contract')->where('id','=',$contractId)->find();
        if(!$contract){
            ajaxReturn(['code'=>301,'msg'=>'合同不存在']);
        }
        if($contract['state'] != 2){
            ajaxReturn(['code'=>302,'msg'=>'未签署完成合同无法作废']);

        }
        if($contract['initiateType'] !=$type && $contract['initiate_id'] != $typeId){
            ajaxReturn(['code'=>302,'msg'=>'操作人不是合同发起人，作废失败']);
        }
        $commoncontract = new Commoncontract();
        $res = $commoncontract->cancelcontract($contractId,$reason);
        if($res['code'] == 200){
            ajaxReturn(['code'=>200,'msg'=>'操作成功']);
        }else{
            ajaxReturn(['code'=>302,'msg'=>'操作失败']);
        }

    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月24月 16:37:14
     * ps:发起合同签署
     * url:{{URL}}/index.php/api/contract/initiatecontract
     */
    public function initiatecontract(){
        $contractId = input('param.contractId');
        if(!$contractId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        $contract = Db::name('contract')->where('id','=',$contractId)->find();
        if($contract['state'] !=10){
            ajaxReturn(['code'=>301,'msg'=>'当前状态不需要发起']);
        }
        //查询状态余额是否充足
        $account = Db::name('account')->where('type','=',$contract['initiateType'])->where('type_id','=',$contract['initiate_id'])->find();
        if($account['contract'] < 1){
            ajaxReturn(['code'=>330,'msg'=>'账户余额不足，发起失败']);
        }

        $data['state'] = 0;
        $commoncontract = new Commoncontract();
        $commoncontract->operatecontract($data,$contract['initiateType'],$contract['initiate_id'],$contractId);
        $commoncontract->initiatesign($contractId);
        ajaxReturn(['code'=>200,'msg'=>'操作成功']);
    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月24月 16:46:07
     * ps:删除合同
     * url:{{URL}}/index.php/api/contract/delcontract
     */
    public function delcontract(){
        $contractId = input('param.contractId');
        if(!$contractId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        $contract = Db::name('contract')->where('id','=',$contractId)->find();
        if($contract['state'] !=10 || $contract['state'] !=3){
            $commoncontract = new Commoncontract();
            $commoncontract->delcontract($contractId);
            ajaxReturn(['code'=>200,'msg'=>'操作成功']);
        }
        ajaxReturn(['code'=>301,'msg'=>'当前状态不能删除合同']);

    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月31月 15:46:51
     * ps:获取签署任务详细信息
     * url:{{URL}}/index.php/api/contract/gettaskdetaill
     */
    public function gettaskdetaill(){
        $contractId = input('param.contractId');
        if(!$contractId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }

        $commoncontract = new Commoncontract();
        $res = $commoncontract->getcontracttask($contractId);
        //dump($res);exit;
        if($res['code'] == 300){
            ajaxReturn(['code'=>302,'msg'=>$res['msg']]);
        }

        $data['signTaskSubject'] = $res['data']['signTaskSubject'];
        $data['signTaskId'] = $res['data']['signTaskId'];
        switch ($res['data']['signTaskStatus']){

            case 'task_created':
                $data['signTaskStatus'] = '创建中';
                break;
            case 'finish_creation':
                $data['signTaskStatus'] = '已创建';
                break;
            case 'fill_progress':
                $data['signTaskStatus'] = '填写中';
                break;
            case 'fill_completed':
                $data['signTaskStatus'] = '填写已完成';
                break;
            case 'sign_progress':
                $data['signTaskStatus'] = '签约中';
                break;
            case 'sign_completed':
                $data['signTaskStatus'] = '已签约';
                break;
            case 'task_finished':
                $data['signTaskStatus'] = '已签约';
                break;
            case 'task_terminated':
                $data['signTaskStatus'] = '已撤销';
                break;
            case 'expired':
                $data['signTaskStatus'] = '已逾期';
                break;
            case 'abolishing':
                $data['signTaskStatus'] = '作废中';
                break;
            case 'revoked':
                $data['signTaskStatus'] = '已作废';
                break;

        }
        if($res['data']['initiator']['idType'] == 'corp'){
            //创建者为企业
            $user = Db::name('enterprise')->where('account','=',$res['data']['initiator']['openId'])->order('name')->find();
        }else{
            //创建者为个人
            $user = Db::name('custom')->where('account','=',$res['data']['initiator']['openId'])->order('name')->find();
        }
        if(!$user){
            $user['name'] = '易网签';
        }
        $data['initiatorMemberName'] = $user['name'];
        $data['startTime'] = date('Y-m-d H:i:s',$res['data']['startTime']/1000);
        $data['deadlineTime'] = date('Y-m-d H:i:s',$res['data']['deadlineTime']/1000);
        $data['autoFillFinalize'] = '自动定稿';
        $data['signing'] = array();
        foreach($res['data']['actors'] as $k=>$v){
            //dump($v);exit;
            $data['signing'][$k]['actorId'] = $v['actorInfo']['actorId'];
            if($v['actorInfo']['actorType'] == 'corp'){
                $data['signing'][$k]['actorType'] = '企业';

                $qsuser = Db::name('enterprise')->where('account','=',$v['actorInfo']['actorOpenId'])->order('name')->find();
                if(!$qsuser){
                    $qsuser = Db::name('contract_signing as c')
                        ->join('enterprise','c.type_id = enterprise.id')
                        ->where('TCN','=',$v['actorInfo']['actorId'])
                        ->where('c.contract_id','=',$contractId)
                        ->order('enterprise.name')->find();

                }
            }else{
                $data['signing'][$k]['actorType'] = '个人';
                $qsuser = Db::name('custom')->where('account','=',$v['actorInfo']['actorOpenId'])->order('name')->find();
                if(!$qsuser){
                    $qsuser = Db::name('contract_signing as c')
                        ->join('custom','c.type_id = custom.id')
                        ->where('TCN','=',$v['actorInfo']['actorId'])
                        ->where('c.contract_id','=',$contractId)
                        ->order('custom.name')->find();
                }
            }
            $data['signing'][$k]['name'] = $qsuser['name'];

            if($v['readStatus'] == 'no_read'){
                $data['signing'][$k]['readStatus'] = '未读';
            }else{
                $data['signing'][$k]['readStatus'] = '已读';
            }

            if($v['joinStatus'] == 'no_read'){
                $data['signing'][$k]['joinStatus'] = '未加入';
            }else{
                $data['signing'][$k]['joinStatus'] = '已加入';
            }
            if($v['signStatus'] == 'wait_sign'){
                $data['signing'][$k]['signstatus'] = '待签署';
            }else if($v['signStatus'] == 'signed'){
                $data['signing'][$k]['signstatus'] = '已签署';
            }
            if($v['signTime']){
                $data['signing'][$k]['signTime'] = date('Y-m-d H:i:s',$v['signTime']/1000);
            }else{
                $data['signing'][$k]['signTime']  = '无';
            }
        }

        ajaxReturn(['code'=>200,'msg'=>'获取成功','data'=>$data]);

    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年11月19月 17:34:33
     * ps:下载合同
     * url:{{URL}}/index.php/api/contract/downloadcontract
     */
    public function downloadcontract(){
        $contractId = input('param.contractId');
        if(!$contractId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        $commoncontract = new Commoncontract();
        $url = $commoncontract->download($contractId);
        if($url){
            ajaxReturn(['code'=>200,'msg'=>'请求成功','url'=>$url]);
        }else{
            ajaxReturn(['code'=>301,'msg'=>'请求失败']);
        }
    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年11月20月 10:09:58
     * ps:合同出证
     * url:{{URL}}/index.php/api/contract/certification
     */
    public function certification(){
        $contractId = input('param.contractId');
        if(!$contractId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        $commoncontract = new Commoncontract();
        $res = $commoncontract->applicationreport($contractId);
        if($res['code'] == 200){
            ajaxReturn(['code'=>200,'msg'=>'获取成功','url'=>$res['url']]);
        }else{
            ajaxReturn(['code'=>301,'msg'=>'网络错误请稍后重试']);
        }
    }
}