<?php
/**
 * Created by PhpStorm.
 * User:lang
 * time:2024年10月22月 11:26:26
 * ps:相对方
 */
namespace app\api\controller;

use app\common\controller\Commonattestation;
use app\common\controller\Commonuser;
use think\Controller;
use think\Db;

class Counterpart extends Gathercontroller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:POST, GET, PUT, DELETE, OPTIONS');
        header('Access-Control-Allow-Credentials: true');
        header('Access-Control-Allow-Headers:*');
        header('Access-Control-Expose-Headers: *');
    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月22月 11:27:16
     * ps:获取相对方列表
     * url:{{URL}}/index.php/api/counterpart
     */
    public function getlist(){
        $type = input('param.type');
        $typeId = input('param.typeId');
        $stafftype = input('param.stafftype');
        $page = input('param.page');
        $limit = input('param.limit');

    }
}