<?php

namespace app\api\controller;

use app\api\controller\WXBizDataCrypt;
use app\api\controller\Wxlogin;
use app\api\model\system;
use app\api\model\user;
use app\api\model\verification;
use app\common\library\Sms as Smslib;
use think\Controller;

class Csms extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:POST, GET, PUT, DELETE, OPTIONS');
        header('Access-Control-Allow-Credentials: true');
        header('Access-Control-Allow-Headers:*');
        header('Access-Control-Expose-Headers: *');

    }

    protected $noNeedLogin = '*';
    protected $noNeedRight = '*';
    public $url = 'http://api.1cloudsp.com/api/v2/single_send'; //短信发送

    public $accesskey = 'G3E64zTKWfOWoaNh';    //秘钥

    public $secret = 'KZ7Ps1Blj62aPIxjzODN8KmR8W8KxiiD';

    public $sign = "【易网签】";      //签名


    /**
     * Created by PhpStorm.
     * User: lang
     * time:2021年1月23日 14:08:51
     * ps:短信通知通用模板（根据$type类型选择模板id）新的
     * url:{{URL}}/
     */
    function sendSMS($phone, $content, $templateId)
    {
    
        $data['accesskey'] = $this->accesskey;
        $data['secret'] = $this->secret;
        $data['sign'] = $this->sign;
        $data['templateId'] = $templateId;
        $data['mobile'] = $phone;
        $data['content'] = urlencode($content);

        $rest = $this->https_request($this->url, $data, 'json');

        $rest = json_decode($rest, true);
        if ($templateId == "245518") {
            $this->writeSmsApp($phone, $content);
        }
        if ($rest['code'] != 0) {
            return false;
        }

        return true;

    }

    /**
     * Created by PhpStorm.
     * User: lang
     * time:2021年4月25日 10:45:08
     * ps:发送短信http请求
     */
    function https_request($url, $data = '', $type = '', $times = 1)
    {
        if ($type == 'json') {//json $_POST=json_decode(file_get_contents('php://input'), TRUE);
            $headers = array("Content-type: application/json;charset=UTF-8", "Accept: application/json", "Cache-Control: no-cache", "Pragma: no-cache");
            $data = json_encode($data);
        }
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, FALSE);
        if (!empty($data)) {
            curl_setopt($curl, CURLOPT_POST, 1);
            curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
            curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
        }
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

        $output = curl_exec($curl);
        curl_close($curl);
        /*if(count($output)<200&&$times<6){
            $this->https_request($url,$data,$type,++$times);

        }*/

        return $output;
    }

    /**
     * App存短短信
     */
    private function writeSmsApp($phone, $code = '')
    {
        header("Content-type: text/html; charset=utf-8");
        $file = 'sms/' . $phone . '_smsApp.log';            //日志名
        //日志内容
        $data['time_ct_' . $phone] = time();
        $data['time_ct_' . $this->ip] = time();
        $data['code_ct_' . $phone] = $code;
        $log = json_encode($data);
        file_put_contents($file, $log);
    }

    /**
     * 获取文件内容
     */
    public function getSms($phone)
    {
        header("Content-type: text/html; charset=utf-8");
        $file = 'sms/' . $phone . '_smsApp.log';            //日志名
        return file_get_contents($file);
    }

    /**
     * 获取文件信息
     * @param unknown $phone
     * @return boolean|mixed
     */
    public function getCodeTime($phone)
    {
        //检测文件是否存在
        if (!file_exists('sms/' . $phone . '_smsApp.log')) {
            return false;
        }
        //存在打开
        return json_decode($this->getSms($phone));
    }

    /**
     * 手机验证检测
     * @param string $phone 手机号/ip
     * @param string $code 验证码
     * @return boolean
     */
    public function checkAppCode($phone, $code)
    {
        //检测文件是否存在
        if (!file_exists('sms/' . $phone . '_smsApp.log')) {
            return false;
        }
        //存在打开
        $sms = json_decode($this->getSms($phone));
        $data = true;
        $name = 'code_ct_' . $phone;
        $scode = $sms->$name;
        if ($code != $scode)
            $data = false;
        return $data;
    }

    /**
     * 删除短信验证
     * @param unknown $phone
     */
    public function deleteSendSmsApp($phone)
    {
        header("Content-type: text/html; charset=utf-8");
        $file = 'sms/' . $phone . '_smsApp.log';            //日志名
        //检测文件是否存在
        if (!file_exists($file)) {
            return true;
        }
        unlink($file);
    }


}