<?php

namespace app\api\controller;

use app\api\controller\WXBizDataCrypt;
use app\api\controller\Wxlogin;
use app\api\model\system;
use app\api\model\user;
use app\api\model\verification;
use app\common\library\Sms as Smslib;
use think\Controller;
use think\Db;

class Csms extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:POST, GET, PUT, DELETE, OPTIONS');
        header('Access-Control-Allow-Credentials: true');
        header('Access-Control-Allow-Headers:*');
        header('Access-Control-Expose-Headers: *');

    }

    protected $noNeedLogin = '*';
    protected $noNeedRight = '*';
    public $url = 'http://api.1cloudsp.com/api/v2/single_send'; //短信发送

    public $accesskey = 'G3E64zTKWfOWoaNh';    //秘钥

    public $secret = 'KZ7Ps1Blj62aPIxjzODN8KmR8W8KxiiD';

    public $sign = "【易网签】";      //签名


    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月25月 13:06:38
     * ps:添加模版
     */
    public function addtemplate($temId){
        $templateId = '304696';
        $template = Db::name('template')->where('id','=',$temId)->find();
        if($template){
            $plate = Db::name('platform_setup')->where('enterprise_id','=',0)->field('informphone')->find();

            $name = '平台';
            if($template['type'] == 'custom'){
                $custom = Db::name('custom')->where('id','=',$template['type_id'])->field('name')->find();
                if($custom['name']){
                    $name = $custom['name'];
                }

            }else{

                $enter = Db::name('enterprise')->where('id','=',$template['type_id'])->field('name')->find();
                $name = $enter['name'];
            }
            if($plate['informphone']){
                $content = $name.'##'.$template['name'];
                $this->sendSMS($plate['informphone'],$content,$templateId,'【易网签】');
            }
        }
        return true;
    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月25月 13:06:38
     * ps:启用模版
     */
    public function templateopen($temId){
        $templateId = '304698';
        $template = Db::name('template')->where('id','=',$temId)->find();
        $sign = $this->sign;
        $platformId = 0;

        if($template){
            $phone = '';
            $name = '平台';
            if($template['type'] == 'custom'){
                $custom = Db::name('custom')->where('id','=',$template['type_id'])->field('phone,name')->find();
                if($custom['phone']){
                    $phone = $custom['phone'];
                }
                $name = $custom['name'];
            }else{
                $plate = Db::name('platform_setup')->where('enterprise_id','=',$template['type_id'])->field('informphone,smsign')->find();
                if($plate['informphone']){
                    $phone = $plate['informphone'];
                }
                $enter = Db::name('enterprise')->where('id','=',$template['type_id'])->field('name')->find();
                $name = $enter['name'];
                if($plate['smsign']){
                    $sign =$plate['smsign'];
                }
                if($plate){
                    $platformId = $template['type_id'];
                }
            }
            if($phone){
                $content = $name.'##'.$template['name']."##".$platformId;
                $this->sendSMS($phone,$content,$templateId,$sign);
            }
        }
        return true;
    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月25月 13:06:25
     * ps:发起合同
     */
    public function initiatecontract($contractId){
        $templateId = '304697';
        $signing = Db::name('contract_signing')->where('contract_id','=',$contractId)->select();
        $contract = Db::name('contract')->where('id','=',$contractId)->field('initiateType,initiate_id,contractName')->find();
        $name = '平台';
        $sign = $this->sign;
        $platformId = 0;
        if($contract['initiateType'] == 'enterprise'){
            $plat = Db::name('platform_setup')->where('enterprise_id','=',$contract['initiate_id'])->field('smsign')->find();
            if($plat['smsign']){
                $sign = $plat['smsign'];
            }
            $enter = Db::name('enterprise')->where('id','=',$contract['initiate_id'])->field('name')->find();
            if($enter['name']){
                $name = $enter['name'];
            }
            if($plat){
                $platformId = $contract['initiate_id'];
            }
        }
        foreach($signing as $k=>$v){
            $custom = Db::name('custom')->where('id','=',$v['custom_id'])->field('phone')->find();
            if($custom['phone']){
                $khname = '用户';
                if($v['type'] == 'custom'){
                    $kh = Db::name('custom')->where('id','=',$v['type_id'])->field('name')->find();
                    if($kh['name']){
                        $khname = $kh['name'];
                    }
                }else{
                    $kh = Db::name('enterprise')->where('id','=',$v['type_id'])->field('name')->find();
                    if($kh['name']){
                        $khname = $kh['name'];
                    }
                }
                $content = $khname."##".$name."##".$contract['contractName']."##".$platformId."##".$contractId;
                $this->sendSMS($custom['phone'],$content,$templateId,$sign);
            }
        }
        return true;
    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月25月 13:06:08
     * ps:合同完成
     */
    public function contractfinish($contractId){
        $templateId = '304711';
        $contract = Db::name('contract')->where('id','=',$contractId)->field('initiateType,initiate_id,contractName')->find();
        $sign = $this->sign;
        $platformId = 0;
        $phone = '';
        if($contract['initiateType'] == 'enterprise'){
            $plat = Db::name('platform_setup')->where('enterprise_id','=',$contract['initiate_id'])->field('informphone,smsign')->find();
            if($plat['smsign']){
                $sign = $plat['smsign'];
            }
            $enter = Db::name('enterprise')->where('id','=',$contract['initiate_id'])->field('name')->find();
            if($enter['name']){
                $name = $enter['name'];
            }
            if($plat){
                $platformId = $contract['initiate_id'];
            }
            if($plat['informphone']){
                $phone = $plat['informphone'];
            }

        }else{
            $custom = Db::name('custom')->where('id','=',$contract['initiate_id'])->field('name')->find();
            $name = $custom['name'];
            $phone = $custom['phone'];
        }
        $content = $name.'##'.$contract['contractName'].'##'.$platformId;
        if($phone){
            $this->sendSMS($phone,$content,$templateId,$sign);
        }
    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月25月 13:07:56
     * ps:新企业注册
     */
    public function newenter($enterId){
        $templateId = '304712';

        $plat = Db::name('platform_setup')->where('enterprise_id','=',0)->field('informphone,smsign')->find();

        $enter = Db::name('enterprise')->where('id','=',$enterId)->find();

        $this->sendSMS($plat['informphone'],$enter['name'],$templateId,$this->sign);

    }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年10月30月 17:30:29
     * ps:短信验证码
     */
    public function login($platfromId,$phone,$code){
        $templateId = 245518;
        $sign = $this->sign;
        if($platfromId){
            $plat = Db::name('platform_setup')->where('enterprise_id','=',$platfromId)->field('informphone,smsign')->find();
            if($plat['smsign']){
                $sign = $plat['smsign'];
            }
        }
        $res = $this->sendSMS($phone,"$code",$templateId,$sign);
        return $res;
    }

    /**
     * Created by PhpStorm.
     * User: lang
     * time:2021年1月23日 14:08:51
     * ps:短信通知通用模板（根据$type类型选择模板id）新的
     * url:{{URL}}/
     */
    function sendSMS($phone, $content, $templateId,$sign)
    {
    
        $data['accesskey'] = $this->accesskey;
        $data['secret'] = $this->secret;
        $data['sign'] =$sign;
        $data['templateId'] = $templateId;
        $data['mobile'] = $phone;
        $data['content'] = urlencode($content);

        $rest = $this->https_request($this->url, $data, 'json');

        $rest = json_decode($rest, true);
        if ($templateId == "245518") {
            $this->writeSmsApp($phone, $content);
        }
        if ($rest['code'] != 0) {
            return false;
        }

        return true;

    }

    /**
     * Created by PhpStorm.
     * User: lang
     * time:2021年4月25日 10:45:08
     * ps:发送短信http请求
     */
    function https_request($url, $data = '', $type = '', $times = 1)
    {
        if ($type == 'json') {//json $_POST=json_decode(file_get_contents('php://input'), TRUE);
            $headers = array("Content-type: application/json;charset=UTF-8", "Accept: application/json", "Cache-Control: no-cache", "Pragma: no-cache");
            $data = json_encode($data);
        }
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, FALSE);
        if (!empty($data)) {
            curl_setopt($curl, CURLOPT_POST, 1);
            curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
            curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
        }
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

        $output = curl_exec($curl);
        curl_close($curl);
        /*if(count($output)<200&&$times<6){
            $this->https_request($url,$data,$type,++$times);

        }*/

        return $output;
    }

    /**
     * App存短短信
     */
    private function writeSmsApp($phone, $code = '')
    {
        header("Content-type: text/html; charset=utf-8");
        $file = 'sms/' . $phone . '_smsApp.log';            //日志名
        //日志内容
        $data['time_ct_' . $phone] = time();
        $data['time_ct_' . $this->ip] = time();
        $data['code_ct_' . $phone] = $code;
        $log = json_encode($data);
        file_put_contents($file, $log);
    }

    /**
     * 获取文件内容
     */
    public function getSms($phone)
    {
        header("Content-type: text/html; charset=utf-8");
        $file = 'sms/' . $phone . '_smsApp.log';            //日志名
        return file_get_contents($file);
    }

    /**
     * 获取文件信息
     * @param unknown $phone
     * @return boolean|mixed
     */
    public function getCodeTime($phone)
    {
        //检测文件是否存在
        if (!file_exists('sms/' . $phone . '_smsApp.log')) {
            return false;
        }
        //存在打开
        return json_decode($this->getSms($phone));
    }

    /**
     * 手机验证检测
     * @param string $phone 手机号/ip
     * @param string $code 验证码
     * @return boolean
     */
    public function checkAppCode($phone, $code)
    {
        //检测文件是否存在
        if (!file_exists('sms/' . $phone . '_smsApp.log')) {
            return false;
        }
        //存在打开
        $sms = json_decode($this->getSms($phone));
        $data = true;
        $name = 'code_ct_' . $phone;
        $scode = $sms->$name;
        if ($code != $scode)
            $data = false;
        return $data;
    }

    /**
     * 删除短信验证
     * @param unknown $phone
     */
    public function deleteSendSmsApp($phone)
    {
        header("Content-type: text/html; charset=utf-8");
        $file = 'sms/' . $phone . '_smsApp.log';            //日志名
        //检测文件是否存在
        if (!file_exists($file)) {
            return true;
        }
        unlink($file);
    }


}