<?php

namespace app\api\controller;

use think\Controller;

/**
 * 接口父类
 */
class Gathercontroller extends Controller
{
    public $platformId = 0;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:POST, GET, PUT, DELETE, OPTIONS');
        header('Access-Control-Allow-Credentials: true');
        header('Access-Control-Allow-Headers:*');
        header('Access-Control-Expose-Headers: *');
        //所属企业
        $platformId = input('param.platformId');
        if($platformId){
            $this->platformId = $platformId;
        }
    }

}
