<?php

namespace app\api\controller;

use app\common\controller\Commonattestation;
use app\common\controller\Commonuser;
use think\Controller;
use think\Db;

class Goods extends Gathercontroller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:POST, GET, PUT, DELETE, OPTIONS');
        header('Access-Control-Allow-Credentials: true');
        header('Access-Control-Allow-Headers:*');
        header('Access-Control-Expose-Headers: *');
    }


    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年9月11月 14:22:54
     * ps:商品列表
     * url:{{URL}}/index.php/api/goods/getgoodslist
     */
   public function getgoodslist(){
        $goods = Db::name('goods')
            ->where('deletetime','=',0)
            ->where('grounding','=',1)
            ->order('price asc,id desc')
            ->select();
        $data = array();
        foreach($goods as $k=>$v){
            $data[$k]['goodsId'] = $v['id'];
            $data[$k]['name'] = $v['name'];
            $data[$k]['image'] = $v['image'];
            $data[$k]['details'] = $v['details'];
            $data[$k]['price'] = $v['price'];
            $data[$k]['contract'] = $v['contract'];
            $data[$k]['template'] = $v['template'];
            $data[$k]['createtime'] = date('Y-m-d H:i:s',$v['createtime']);
        }
        ajaxReturn(['code'=>200,'msg'=>'获取成功','data'=>$data]);
   }

    /**
     * Created by PhpStorm.
     * User:lang
     * time:2024年11月11月 9:35:55
     * ps:商品详情
     * url:{{URL}}/index.php/api/goods/getgoodsdetails
     */
   public function getgoodsdetails(){
        $goodsId = input('param.goodsId');
        if(!$goodsId){
            ajaxReturn(['code'=>300,'msg'=>'缺少参数']);
        }
        $goods = Db::name('goods')->where('id','=',$goodsId)->find();
        if(!$goods){
            ajaxReturn(['code'=>301,'msg'=>'商品不存在']);
        }
        $data = array();
        $data['goodsId'] = $goods['id'];
        $data['name'] = $goods['name'];
        $data['image'] = $goods['image'];
        $data['details'] = $goods['details'];
        $data['crossedprice'] = $goods['crossedprice'];
        $data['price'] = $goods['price'];
        $data['contract'] = $goods['contract'];
        $data['template'] = $goods['template'];
        $data['createtime'] = date('Y-m-d',$goods['createtime']);
        ajaxReturn(['code'=>200,'msg'=>'获取成功','data'=>$data]);
   }



}