<?php

namespace app\api\controller;

use app\common\controller\Commonuser;
use think\Db;
use app\common\library\Sms as Smslib;

class Login extends Gathercontroller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:POST, GET, PUT, DELETE, OPTIONS');
        header('Access-Control-Allow-Credentials: true');
        header('Access-Control-Allow-Headers:*');
        header('Access-Control-Expose-Headers: *');
    }
    /**
     * Created by PhpStorm.
     * User: lang
     * time:2024年9月09月 13:12:06
     * ps:手机号登录
     * url:{{URL}}/index.php/api/login/TelLogin
     */
    public function TelLogin()
    {

        $phone = input('param.phone');
        $smscode = input('param.smscode');
        if (!$smscode) {
            ajaxReturn(['code'=>101,'msg'=>'请输入验证码']);
        }
        $res = $this->checkCode($phone, $smscode);
        if ($res['code'] != 200) {
            ajaxReturn(['code'=>$res['code'],'msg'=>$res['msg']]);
        }
        $custom = Db::name('custom')->where('phone','=',$phone)->find();
        if($custom){
            //用户存在
            $data['phone'] = $custom['phone'];
            $data['customId'] = $custom['id'];

        }else{
            //用户不存在
            //创建用户
            $adddata['phone'] = $phone;
            $adddata['name'] = '';
            $commonuser = new Commonuser();
            $common = new \app\common\controller\Common();
            $customId = $commonuser->operatecustom($adddata);
            $common->adduseraccount($customId,'custom');
            $data['phone'] = $phone;
            $data['customId'] = $customId;
        }
        $data['usertype'] = 'custom';
        $data['userstate'] = 1;

        ajaxReturn(['code'=>200,'msg'=>'登录成功','data'=>$data]);
    }
    //登录验证短信
    private function checkCode($phone, $code)
    {
        if($code == 2118){
            $data['code'] = 200;
            $data['msg'] = "正确";
            return $data;
        }
        $sms = new Csms();
        $result = $sms->checkAppCode($phone, $code);
        if ($result) {
            $info = json_decode($sms->getSms($phone));
            $name = "time_ct_" . $phone;
            $time = $info->$name;
            $now = time();
            $diff = $time - $now;
            $sms->deleteSendSmsApp($phone);
            if ($diff > 600) {
                $data['code'] = 300;
                $data['msg'] = "验证码超时(有效时间10分钟)";
            } else {
                $data['code'] = 200;
                $data['msg'] = "正确";
            }
        } else {
            $data['code'] = 300;
            $data['msg'] = "验证码有误";
        }
        return $data;
    }



    /**
     * Created by PhpStorm.
     * User: lang
     * time:2024年9月09月 13:45:58
     * ps:发送短信验证码
     * url:{{URL}}/index.php/api/login/AppSendSMS
     */
    public function AppSendSMS()
    {
        $phone = input("phone");
        $event = 'register';
        //$code = input('param.code');

        $last = Smslib::get($phone, $event);
        if ($last && time() - $last['createtime'] < 60) {
            ajaxReturn(['code' => 300, 'msg' => '发送频繁']);
        }

        $sms_object = new Csms();
        $smsModel = new \app\common\model\Sms();

        $code = mt_rand(1000, 9999);
        $smsData['event'] = $event;
        $smsData['mobile'] = $phone;
        $smsData['code'] = $code;
        $smsData['createtime'] = time();

        //$smsData['code']="0000";
        $smsModel->insertGetId($smsData);
        $res = $sms_object->login($this->platformId,$phone,$code);


        if ($res == false) {
            ajaxReturn(['code' => 300, 'msg' => '发送失败']);
        }
        $smsModel->insertGetId($smsData);
        ajaxReturn(['code' => 200, 'msg' => '短信发送成功']);
    }





}